[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lilacs"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--cov-report=term-missing",
    "--cov=src",
    "--cov-branch",
]
