[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lilacs"
version = "0.0.1"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--cov-report=term-missing",
    "--cov=lilacs",
    "--cov-branch",
]
